# примеры API-запросов

# получение списка товаров
GET localhost:8000/api/v1/products/
Content-Type: application/json

# добавление товара
POST localhost:8000/api/v1/products/
Content-Type: application/json
{
    "name": "Some product",
    "description": "Awesome product",
    "price": 100
}

# карточка товара
GET localhost:8000/api/v1/products/1/
Content-Type: application/json

# получение отзывов
GET localhost:8000/api/v1/product-reviews/
Content-Type: application/json

# новый отзыв
POST localhost:8000/api/v1/product-reviews/
Content-Type: application/json
{
    "user": 2,
    "product": 1,
    "text": "Awesome product",
    "mark": 4
}

# заказы
GET localhost:8000/api/v1/orders/
Content-Type: application/json

# новый заказ
POST localhost:8000/api/v1/product-reviews/
Content-Type: application/json
{
    "user": 2,
    "products":[ {"product": 2, "quantity": 5 } ]
}

# подборки
GET localhost:8000/api/v1/product-collections/
Content-Type: application/json
