# Generated by Django 3.2.4 on 2021-06-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='order',
            new_name='name',
        ),
    ]
